name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  # Job 1: For linting the commit message
  commitlint:
    name: Commit Message Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Required for commitlint to analyze commit history
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        # Assumes @commitlint/cli and config are in your package.json devDependencies
        run: npm ci

      - name: Validate current commit (on push)
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits (on pull_request)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  # Job 2: For linting the code
  eslint:
    name: ESLint Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        # Assumes you have a "lint" script in your package.json, like "eslint ."
        run: npm run lint
